# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "centos64"
  config.vm.network :hostonly, "10.45.0.10"

  config.vm.forward_port 8000, 8085

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["./cookbooks"]
    chef.roles_path = "./roles"
    chef.add_role "gearman_dashboard"
	chef.json = JSON.parse(IO.read("overrides.json"))
  end
  
end
