# php from rightscale-epel repo
package "php53u"
package "php53u-mysql"
package "php53u-mcrypt"
package "php53u-gd"
package "php53u-imap"
package "php53u-pecl-memcache"
package "php53u-mbstring"
package "php53u-pecl-imagick"
package "php53u-xml"
